void setupTimer (uint32_t period);
void setupDAC ();
void setupNVIC ();
void setupGPIO ();
void startTimer ();
void stopTimer ();
void initializeSounds ();
void enableEM4 ();
void enableEM1 ();
void disableRAMBlocks ();
